version: '3.3'

services:
    wordpress:
        image: wordpress
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: test
            WORDPRESS_DB_PASSWORD: test
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_SITE_URL: 'localhost'
            WORDPRESS_SITE_DESCRIPTION: 'A child theme for a Wordpress site.'
            WORDPRESS_ADMIN_USER: test
            WORDPRESS_ADMIN_PASSWORD: test
            WORDPRESS_ADMIN_EMAIL: test@test.com
        volumes:
            - ./wordpress:/var/www/html
            - ./themes/wprig:/var/www/html/wp-content/themes/wprig
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./mysql:/var/lib/mysql

volumes:
    wordpress:
    mysql:
